[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "instagram"
  weight = 2
  url = "https://www.instagram.com/j_rad_k/"
[[social]]
  name = "strava"
  weight = 3
  url = "https://www.strava.com/athletes/4787189"
[[social]]
  name = "linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/jared-kosanovic-98671310a"
[[social]]
  name = "github"
  weight = 5
  url = "https://github.com/jaredkosanovic"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"